name: Languages Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]  # Ежедневное обновление
  workflow_dispatch:                  # Ручной запуск

permissions:
  contents: write
  
jobs:
  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg      # Имя выходного файла
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""

          plugin_languages: yes        # Активировать плагин
          plugin_languages_ignored: jupyter notebook, html  # Исключить Jupyter
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8    # Макс. языков
