name: Languages Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]  # Ежедневное обновление
  workflow_dispatch:                  # Ручной запуск

permissions:
  contents: write
  
jobs:
  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: languages.svg      # Имя выходного файла
          base_skip: yes

          plugin_languages: yes        # Активировать плагин
          plugin_languages_details: "lines, percentage"
          plugin_languages_limit: 8    # Макс. языков
          plugin_languages_ignored: jupyter notebook, html  # Исключить
          